id = "llvm"
name = "LLVM IR"
version = "0.1.0"
schema_version = 1
authors = ["DaniPopes"]
description = "LLVM Intermediate Representation (IR) support"
repository = "https://github.com/DaniPopes/zed-llvm"
categories = ["languages"]

[grammars.llvm]
repository = "https://github.com/benwilliamgraham/tree-sitter-llvm"
rev = "2914786ae6774d4c4e25a230f4afe16aa68fe1c1"
