name = "LLVM IR"
grammar = "llvm"
path_suffixes = ["ll", "llvm"]
first_line_pattern = "^\\s*;\\s*ModuleID"
line_comments = ["; "]
tab_size = 2
autoclose_before = ";:.,=}])>"
word_characters = ["-", ".", ":", "/", "\\", "+", "=", "@", "#", "\"", "'"]
collapsed_placeholder = "; ..."
brackets = [
    { start = "(", end = ")", close = true, newline = true },
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
    { start = "'", end = "'", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
]
